from enum import StrEnum


class SettingEnum(StrEnum):
    """
    Список наименований настроек системы
    """
    EMAIL_SMTP_HOST = "EMAIL_SMTP_HOST"
    EMAIL_SMTP_PORT = "EMAIL_SMTP_PORT"
    EMAIL_SMTP_LOGIN = "EMAIL_SMTP_LOGIN"
    EMAIL_SMTP_PASSWORD = "EMAIL_SMTP_PASSWORD"

    PRESENTATION_ORIGIN_HOST = "PRESENTATION_ORIGIN_HOST"

    ACCESS_TOKEN_SECRET_KEY = "ACCESS_TOKEN_SECRET_KEY"
    ACCESS_TOKEN_ALGORITHM = "ACCESS_TOKEN_ALGORITHM"



